ToBeOtt/TheRestaurant

TheRestaurant/TheRestaurant.Presentation/Client/Components/Themes/TheRestaurantColorTheme.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/AdminNavMenu.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/HeaderNavBar.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/MainLayout.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/NavbarDrawer.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/UserNavMenu.razor
TheRestaurant/TheRestaurant.Presentation/Client/wwwroot/index.html

Added Fonts to the index.html so they are shared across the app.
Basic Mudblazor ColorTheme Setup.

MudBlazor Fontimport

---

TheRestaurant/TheRestaurant.Presentation/Client/Components/Themes/TheRestaurantColorTheme.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/MainLayout.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/ThemeReference.razor

Added a reference component to show examples and fonts

MudThemeSetup

---

TheRestaurant/TheRestaurant.Common.Infrastructure/Data/RestaurantDbContext.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedAllergy.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedCategories.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231123121056_AllergySeed.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231123121056_AllergySeed.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231123122940_CategorySeed.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231123122940_CategorySeed.cs

Seeded both the Allergies table with 10 most common food allergies  and the Categories table with  17 different categories.

Seed Allergy and Categories

---

TheRestaurant/TheRestaurant.Common.Infrastructure/Data/RestaurantDbContext.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedOrderStatus.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231123130034_OrderStatusSeed.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231123130034_OrderStatusSeed.cs

Added
{ 1, "Pending" },
{ 2, "Processing" },
{ 3, "Delivered" },
{ 4, "Cancelled" }

Seed for OrderStatus

---

TheRestaurant/TheRestaurant.Presentation/Client/App.razor
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/AuthService.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/ClientServiceConfig.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/RoleService.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/TokenExpirationChecker.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Authentication/Login/LoginForm.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Authentication/Registration/RegisterForm.razor
TheRestaurant/TheRestaurant.Presentation/Client/Helpers/TokenHelper.cs
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Authentication/Logout.razor
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Index.razor
TheRestaurant/TheRestaurant.Presentation/Client/Program.cs
TheRestaurant/TheRestaurant.Presentation/Client/ServerAuthenticationStateProvider.cs
TheRestaurant/TheRestaurant.Presentation/Client/Shared/AdminNavMenu.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/UserNavMenu.razor
TheRestaurant/TheRestaurant.Presentation/Client/TheRestaurant.Presentation.Client.csproj
TheRestaurant/TheRestaurant.Presentation/Server/Controllers/Authentication/AuthenticationController.cs

Fixed small errors, added better token exp timer etc

minor fixes

---

TheRestaurant/TheRestaurant.Presentation/Server/Config/Swagger/SwaggerServicesConfig.cs
TheRestaurant/TheRestaurant.Presentation/Server/Program.cs
TheRestaurant/TheRestaurant.Presentation/Server/TheRestaurant.Presentation.Server.csproj

Swiggity swhooty... swagger is coming for that booty...

Add swagger

---

TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Allergies/CreateAllergy.razor

Fixed button and validation on the Dialogform for Create Allergy

Fixed Validation

---

TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Allergies/UpdateAllergy.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Allergies/ViewAllergies.razor

Create allergy fix create

---

TheRestaurant/TheRestaurant.Presentation/Client/Shared/Admin/AdminNav.razor

Updated to Swedish.
Updated Icons
Removed submenu for Allergy

Updated Admin Nav

---

TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Allergies/ViewAllergies.razor

Added Permissions to:
Create, edit and delete allergies

Added Permissions

---

TheRestaurant/TheRestaurant.Application/ApplicationServicesConfig.cs
TheRestaurant/TheRestaurant.Application/Dashboard/DashboardServices.cs
TheRestaurant/TheRestaurant.Application/Dashboard/Interfaces/IDashboardRepository.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/InfrastructureDataConfig.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Repositories/Dashboard/DashboardRepository.cs
TheRestaurant/TheRestaurant.Contracts/Responses/OrderCountResponse.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServiceConfig.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/ClientDashboardServices.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Dashboard/CategoriesPieChart.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Dashboard/OrderListChart.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Dashboard/ProductsDonutChart.razor
TheRestaurant/TheRestaurant.Presentation/Client/Pages/About/AboutPage.razor
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Admin/Dashboard/Index.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/Admin/AdminNav.razor
TheRestaurant/TheRestaurant.Presentation/Client/Shared/AdminNavMenu.razor
TheRestaurant/TheRestaurant.Presentation/Server/Controllers/Admin/DashboardController.cs
TheRestaurant/TheRestaurant.Presentation/Shared/DTO/Dashboard/OrderCountDto.cs

- Setup page and component for dashboard.
- Made suggestion for MudBlazor charts to use. Rigged backend for above.

rigged UI for dashboard

---

TheRestaurant/TheRestaurant.Application/ApplicationServicesConfig.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/OrderConfig.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/RestaurantDbContext.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231205125041_orderentity-updates.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231205125041_orderentity-updates.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231205132559_EmployeeNullable.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231205132559_EmployeeNullable.cs
TheRestaurant/TheRestaurant.Domain/Entities/Authentication/Employee.cs
TheRestaurant/TheRestaurant.Domain/Entities/OrderEntities/EmployeeOrder.cs
TheRestaurant/TheRestaurant.Domain/Entities/OrderEntities/Order.cs
TheRestaurant/TheRestaurant.Domain/Entities/OrderEntities/OrderRow.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/ClientCartService.cs
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Order/OrderDTO/OrderDTO.cs
TheRestaurant/TheRestaurant.Presentation/Server/Controllers/Order/OrderController.cs

Order configure

---

TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/TakePendingOrder.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/ViewPendingOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Admin/Order/PendingOrders.razor

Pending Order Pages view component set as far as possible... mockdata in it for now

Page to View All New/Pending Orders

---

TheRestaurant/TheRestaurant.Common.Infrastructure/Data/RestaurantDbContext.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedOrder.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedOrder2.cs

Seed order2

---

TheRestaurant/TheRestaurant.Application/Orders/Interfaces/IOrderRepository.cs
TheRestaurant/TheRestaurant.Application/Orders/OrderService.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/RestaurantDbContext.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Repositories/Orders/OrderRepository.cs
TheRestaurant/TheRestaurant.Contracts/Responses/Orders/ActiveOrdersResponse.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/ClientOrderService.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrderCompleteDialog.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/ViewActiveOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Admin/Order/ActiveOrders.razor
TheRestaurant/TheRestaurant.Presentation/Server/Controllers/Order/OrderController.cs
TheRestaurant/TheRestaurant.Presentation/Shared/DTO/Orders/ActiveOrdersDto.cs

- Added view active orders
- Dialog for confirmation
- Change status of order being finished

Implemented active order

---

TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedOrder2.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231207142034_OrderSeed2.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231207142034_OrderSeed2.cs
TheRestaurant/TheRestaurant.Domain/Entities/Orders/OrderStatus.cs

TODO - make sure productSeeding runs first, then orderseeding.

Refactored orderSeeding

---

TheRestaurant/TheRestaurant.Application/Interfaces/IProduct/IProductRepository.cs
TheRestaurant/TheRestaurant.Application/Orders/OrderService.cs
TheRestaurant/TheRestaurant.Application/Services/ProductServices/ProductService.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/RestaurantDbContext.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedProduct.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231211070609_VAT.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231211070609_VAT.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231211075311_AdjustedPricesForSeeds.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231211075311_AdjustedPricesForSeeds.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231211075827_fixedRoundingOnPriceForProducts.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231211075827_fixedRoundingOnPriceForProducts.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Repositories/Orders/OrderRepository.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Repositories/Product/ProductRepository.cs
TheRestaurant/TheRestaurant.Contracts/Requests/Order/GetReceiptRequest.cs
TheRestaurant/TheRestaurant.Contracts/Requests/Product/CreateProductRequest.cs
TheRestaurant/TheRestaurant.Contracts/Responses/Orders/GetReceiptResponse.cs
TheRestaurant/TheRestaurant.Domain/Entities/Menu/Product.cs
TheRestaurant/TheRestaurant.Domain/Entities/Menu/VAT.cs
TheRestaurant/TheRestaurant.Presentation/Client/ClientServices/ClientOrderService.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersFinished/ReceiptDialog.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersFinished/ViewFinishedOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/ProductCrud/CreateProduct.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Menu/MenuItemCard.razor
TheRestaurant/TheRestaurant.Presentation/Server/Controllers/Order/OrderController.cs

- Added receipt-functionality - Added VAT and PriceBeforeVAT properties to Product.
Fixed bug with sorting of products

FinshedBranch

---

TheRestaurant/TheRestaurant.Application/Orders/OrderService.cs
TheRestaurant/TheRestaurant.Contracts/DTOs/OrderDTOs/PendingOrderDto.cs
TheRestaurant/TheRestaurant.Contracts/Responses/Orders/PendingOrdersResponse.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/TakePendingOrder.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/ViewPendingOrders.razor

Display ordercomment on pending orderview and Takeorder component

Display ordercomment on pending order

---

TheRestaurant/TheRestaurant.Application/Orders/OrderService.cs
TheRestaurant/TheRestaurant.Contracts/Responses/Orders/ActiveOrdersResponse.cs
TheRestaurant/TheRestaurant.Contracts/Responses/Orders/FinishedOrderResponse.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrderComment.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrderDetailsDialog.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersFinished/ViewFinishedOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersPending/TakePendingOrder.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersPending/ViewPendingOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersProcessed/ViewActiveOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Pages/Admin/Order/PendingOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/TheRestaurant.Presentation.Client.csproj
TheRestaurant/TheRestaurant.Presentation/Shared/DTO/Orders/ActiveOrdersDto.cs
TheRestaurant/TheRestaurant.Presentation/Shared/DTO/Orders/FinishedOrderDto.cs

Comment added to all views in Admin Order UI

Add comment to admin order UI

---

TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrderDeleteDialog.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersPending/ViewPendingOrders.razor

In pending order (nya order) you now have the options to delete the order

OrderDelete

---

TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedAllergy.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231218155919_UpdateAllergiesToSwe.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231218155919_UpdateAllergiesToSwe.cs

AllergyToSwe

---

TheRestaurant/TheRestaurant.Common.Infrastructure/Data/SeedData.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231219083836_CategorySeedToSwe.Designer.cs
TheRestaurant/TheRestaurant.Common.Infrastructure/Migrations/20231219083836_CategorySeedToSwe.cs

CategorySweSeed
Update so that all categories are in swedish

CategorySweSeed

---

TheRestaurant/TheRestaurant.Application/Orders/OrderService.cs
TheRestaurant/TheRestaurant.Contracts/DTOs/OrderDTOs/PendingOrderDto.cs
TheRestaurant/TheRestaurant.Contracts/Responses/Orders/ActiveOrdersResponse.cs
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersPending/TakePendingOrder.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersPending/ViewPendingOrders.razor
TheRestaurant/TheRestaurant.Presentation/Client/Components/Admin/Orders/OrdersProcessed/OrderCompleteDialog.razor
TheRestaurant/TheRestaurant.Presentation/Server/Controllers/Order/OrderController.cs

Displays the sizes of clothes on all the order views, and when CU gets status on the order.

Size displayed on order
